site_name: GNPS2 Documentation
site_url: https://wang-bioinformatics-lab.github.io/GNPS2_Documentation/
edit_uri: https://github.com/Wang-Bioinformatics-Lab/GNPS2_Documentation/edit/master/docs/
repo_name: Wang-Bioinformatics-Lab/GNPS2_Documentation
repo_url: https://github.com/Wang-Bioinformatics-Lab/GNPS2_Documentation

nav:
    - About: index.md
    - Server Status: status.md
    - Accounts: accounts.md
    - FAQ: faq.md
    - GNPS2 Interface:
        - GNPS2 Tasks: workflowtasks.md
    - Data Reanalysis: datareanalysis.md
    - Data Preparation/Upload:
        - File Formats: dataformats.md
        - File Conversion: fileconversion.md
        - Agilent: agilent_conversion.md
        - Waters: waters_conversion.md
        - File Upload: fileupload.md
        - Metadata: metadata.md
    - Overall Tool Index: toolindex.md
    - Analysis Workflow Index: workflowindex.md
    - GNPS2 USI: usi.md
    - IDBac:
        - Start Here: idbac-start-here.md 
        - Request an Account: idbac-request-an-account.md
        - Office Hours: idbacofficehours.md
        - Database Depositions: idbacdepositions.md
        - Sumbit Data for Analysis: idbacsumbmitdata.md
        - Analysis Platform: idbacanalysisplatform.md
        - Data Conversion - Raw Bruker: idbacrawconversion.md
        - Data Conversion - non Bruker: idbacmsconvertfilemerger.md
        - Data Conversion - mzXML to mzML: idbacmzxmlconversion.md
        
    - Tandem Mass Spectrometry Data Analysis:
        - Classical Molecular Networking: classical.md
        - FBMN:
            - FBMN: fbmn.md
            - Agilent: agilent_fbmn.md
            - Progenesis: fbmn-with-progenesisqi.md
            - Protocols for FBMN:
                - Step by Step Protocols for Progenesis Data: protocol_fbmn_progenesis_overlay.md
        - ModiFinder: modifinder.md
        - Networking Overlay: Networkingoverlay.md
        - Network Topology - Transitive Alignments: transitive.md
        - Multiple Spectrum Alignment: mmsa.md
    - Spectral Libraries:
        - Using Spectral Libraries in GNPS2: libraries.md
    - GNPS2 MASST: masst.md
    - GNPS2 Dataset Explorer: gnpsdatasetexplorer.md
    - GNPS2 PanReDU:
        - ReDU Overview: ReDU_overview.md
        - ReDU Data Selection: ReDU_Dataselection_dashboard.md
        - ReDU Contribution: ReDU_Contribution.md
        - Pan Repo Public Data Downloader: downloadpublicdata.md
    - GNPS2 Quickstart2: quickstart2.md
    - API: api.md
    - Logos: logo.md
    - GNPS2 Workshops: workshops.md
    - GNPS2 Workflow Development: workflowdev.md
    - Join the GNPS2 community: community.md
    - Contact/Office Hours: contact.md

    
theme:
    name: material
    palette:
        primary: '#003DA5'
        accent: '#FFB81C'
    custom_dir: overrides
    features:
      - content.action.edit
    
extra:
    social:
        - type: 'github'
          link: 'https://github.com/Wang-Bioinformatics-Lab'

plugins:
    - search
    - git-revision-date-localized:
        type: datetime
    - mermaid2
    - glightbox


markdown_extensions:
    - toc:
        permalink: true
    - admonition
    - pymdownx.details
    - pymdownx.superfences:
        # make exceptions to highlighting of code:
        custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:mermaid2.fence_mermaid

extra:
  analytics:
    provider: umami
